$(document).ready(function(){
	
	function fromHexValue($value){
		var $code = 'n';
		if($value == '1') $code = 'r';
		if($value == '2') $code = 'b';
		if($value == '3') $code = 'l';
		if($value == '4') $code = 'p';
		if($value == '5') $code = 'pe';
		if($value == '6') $code = 'se';
		if($value == '7') $code = 'x';
		if($value == '8') $code = 'sl';
		if($value == '9') $code = 'g';
		if($value == 'A') $code = 'pr';
		if($value == 'B') $code = 'di';
		if($value == 'C') $code = 'sn';
		if($value == 'D') $code = 'o';
		if($value == 'E') $code = 'bk';
		return $code;
	}
	
	$odontogram = 'id=' + $('#id').val();
	$.post('modules/getodontogram.php',$odontogram,function(data){
	
		//d1
		$code = fromHexValue(data.d18.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d18t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d18.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d18l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d18.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d18b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d18.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d18r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d18.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d18c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d18.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d18s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d17.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d17t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d17.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d17l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d17.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d17b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d17.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d17r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d17.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d17c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d17.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d17s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d16.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d16t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d16.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d16l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d16.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d16b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d16.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d16r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d16.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d16c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d16.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d16s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d15.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d15t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d15.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d15l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d15.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d15b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d15.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d15r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d15.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d15c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d15.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d15s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d14.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d14t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d14.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d14l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d14.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d14b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d14.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d14r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d14.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d14c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d14.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d14s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d13.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d13t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d13.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d13l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d13.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d13b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d13.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d13r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d13.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d13c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d13.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d13s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d12.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d12t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d12.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d12l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d12.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d12b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d12.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d12r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d12.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d12c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d12.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d12s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d11.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d11t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d11.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d11l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d11.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d11b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d11.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d11r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d11.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d11c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d11.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d11s').attr('src','images/odontogram/' + $code + '.png');
		
		//d2
		$code = fromHexValue(data.d21.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d21t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d21.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d21l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d21.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d21b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d21.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d21r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d21.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d21c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d21.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d21s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d22.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d22t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d22.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d22l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d22.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d22b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d22.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d22r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d22.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d22c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d22.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d22s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d23.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d23t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d23.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d23l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d23.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d23b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d23.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d23r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d23.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d23c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d23.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d23s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d24.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d24t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d24.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d24l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d24.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d24b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d24.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d24r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d24.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d24c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d24.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d24s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d25.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d25t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d25.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d25l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d25.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d25b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d25.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d25r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d25.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d25c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d25.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d25s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d26.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d26t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d26.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d26l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d26.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d26b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d26.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d26r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d26.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d26c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d26.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d26s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d27.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d27t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d27.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d27l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d27.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d27b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d27.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d27r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d27.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d27c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d27.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d27s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d28.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d28t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d28.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d28l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d28.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d28b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d28.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d28r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d28.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d28c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d28.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d28s').attr('src','images/odontogram/' + $code + '.png');
		
		//d5
		$code = fromHexValue(data.d55.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d55t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d55.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d55l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d55.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d55b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d55.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d55r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d55.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d55c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d55.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d55s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d54.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d54t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d54.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d54l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d54.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d54b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d54.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d54r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d54.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d54c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d54.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d54s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d53.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d53t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d53.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d53l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d53.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d53b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d53.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d53r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d53.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d53c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d53.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d53s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d52.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d52t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d52.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d52l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d52.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d52b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d52.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d52r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d52.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d52c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d52.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d52s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d51.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d51t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d51.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d51l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d51.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d51b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d51.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d51r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d51.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d51c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d51.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d51s').attr('src','images/odontogram/' + $code + '.png');
		
		//d6
		$code = fromHexValue(data.d61.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d61t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d61.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d61l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d61.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d61b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d61.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d61r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d61.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d61c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d61.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d61s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d62.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d62t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d62.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d62l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d62.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d62b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d62.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d62r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d62.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d62c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d62.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d62s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d63.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d63t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d63.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d63l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d63.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d63b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d63.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d63r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d63.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d63c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d63.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d63s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d64.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d64t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d64.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d64l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d64.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d64b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d64.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d64r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d64.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d64c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d64.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d64s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d65.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d65t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d65.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d65l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d65.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d65b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d65.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d65r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d65.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d65c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d65.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d65s').attr('src','images/odontogram/' + $code + '.png');
		
		//d8
		$code = fromHexValue(data.d85.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d85t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d85.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d85l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d85.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d85b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d85.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d85r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d85.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d85c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d85.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d85s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d84.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d84t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d84.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d84l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d84.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d84b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d84.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d84r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d84.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d84c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d84.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d84s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d83.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d83t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d83.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d83l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d83.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d83b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d83.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d83r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d83.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d83c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d83.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d83s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d82.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d82t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d82.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d82l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d82.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d82b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d82.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d82r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d82.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d82c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d82.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d82s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d81.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d81t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d81.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d81l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d81.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d81b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d81.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d81r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d81.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d81c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d81.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d81s').attr('src','images/odontogram/' + $code + '.png');
		
		//d7
		$code = fromHexValue(data.d71.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d71t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d71.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d71l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d71.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d71b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d71.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d71r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d71.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d71c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d71.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d71s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d72.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d72t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d72.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d72l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d72.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d72b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d72.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d72r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d72.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d72c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d72.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d72s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d73.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d73t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d73.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d73l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d73.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d73b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d73.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d73r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d73.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d73c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d73.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d73s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d74.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d74t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d74.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d74l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d74.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d74b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d74.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d74r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d74.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d74c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d74.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d74s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d75.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d75t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d75.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d75l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d75.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d75b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d75.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d75r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d75.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d75c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d75.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d75s').attr('src','images/odontogram/' + $code + '.png');
		
		//d4
		$code = fromHexValue(data.d48.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d48t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d48.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d48l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d48.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d48b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d48.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d48r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d48.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d48c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d48.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d48s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d47.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d47t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d47.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d47l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d47.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d47b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d47.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d47r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d47.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d47c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d47.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d47s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d46.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d46t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d46.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d46l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d46.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d46b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d46.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d46r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d46.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d46c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d46.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d46s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d45.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d45t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d45.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d45l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d45.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d45b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d45.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d45r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d45.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d45c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d45.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d45s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d44.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d44t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d44.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d44l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d44.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d44b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d44.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d44r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d44.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d44c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d44.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d44s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d43.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d43t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d43.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d43l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d43.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d43b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d43.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d43r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d43.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d43c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d43.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d43s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d42.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d42t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d42.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d42l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d42.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d42b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d42.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d42r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d42.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d42c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d42.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d42s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d41.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d41t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d41.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d41l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d41.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d41b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d41.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d41r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d41.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d41c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d41.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d41s').attr('src','images/odontogram/' + $code + '.png');
		
		//d3
		$code = fromHexValue(data.d31.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d31t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d31.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d31l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d31.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d31b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d31.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d31r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d31.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d31c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d31.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d31s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d32.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d32t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d32.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d32l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d32.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d32b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d32.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d32r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d32.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d32c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d32.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d32s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d33.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d33t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d33.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d33l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d33.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d33b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d33.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d33r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d33.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d33c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d33.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d33s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d34.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d34t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d34.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d34l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d34.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d34b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d34.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d34r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d34.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d34c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d34.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d34s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d35.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d35t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d35.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d35l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d35.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d35b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d35.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d35r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d35.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d35c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d35.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d35s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d36.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d36t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d36.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d36l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d36.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d36b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d36.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d36r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d36.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d36c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d36.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d36s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d37.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d37t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d37.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d37l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d37.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d37b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d37.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d37r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d37.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d37c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d37.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d37s').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d38.charAt(0));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 't' + $code;
		$('#d38t').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d38.charAt(1));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'l' + $code;
		$('#d38l').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d38.charAt(2));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'b' + $code;
		$('#d38b').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d38.charAt(3));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'r' + $code;
		$('#d38r').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d38.charAt(4));
		if($code == 'r' || $code == 'b' || $code == 'l' || $code == 'p' || $code == 'g' || $code == 'o') $code = 'c' + $code;
		$('#d38c').attr('src','images/odontogram/' + $code + '.png');
		$code = fromHexValue(data.d38.charAt(5));
		if($code == 'n') $code = 'bk';
		$('#d38s').attr('src','images/odontogram/' + $code + '.png');
		
	},'json');
}); 